baseURL = "https://michael-freling.github.io"
languageCode = "en-us"
title = "Notes for self made anime"
enableRobotsTXT = true

# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme = ["github.com/onweru/compose"] # edit this if you'ld rather use a fork of this repo
# theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:sections/:year/:month/:day/:slug/"

#  menu items
[[menu.main]]
  name = "Top"
  weight = 2
  url = "/"

#  menu items
# [[menu.main]]
#   name = "Docs"
#   weight = 2
#   url = "/docs/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 1
    startLevel = 1

# Everything below this are Site Params

[params]

  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true # set to false to disable darkmode by default # user will still have the option to use dark mode

  # sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable
  codeMaxLines = 7

  # disable showing line numbers by default. Switch to `true` if you'd rather have them on.
  codeLineNumbers = false

# # Site logo
  [params.logo]
    lightMode = "/icons/moon.svg"
    darkMode = "/icons/sun.svg"

  # # optional
  # # attribution. Feel free to delete this
  # [params.author]
  #   name = "Weru"
  #   url = "https://neuralvibes.com/author/"

[params.source]
  iconLight = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
  iconDark = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
  url = "https://github.com/michael-freling/michael-freling.github.io"

# Enable search
[outputs]
   home = ["HTML", "RSS","JSON"]
